base_path: /extension
commit_message: 'Fix:  New translations for (%language%) from Crowdin.  [ci skip]'
append_commit_message: false
files:
  - source: /_locales/en/*.json
    translation: /_locales/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
