blank_issues_enabled: false
contact_links:
  - name: Discussion - For new support issues
    url: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/discussions/new
    about: A new way of interacting with our community (in beta).  New support issues and feature requests can be created and discussed here.
  - name: Documentation
    url: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation
    about: Make sure that you have already read the Documentation on the available features and what they do.
  - name: FAQ - Common Questions and Issues
    url: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues
    about: Please check to see if your question/issue has been answered already!
