const constants = {
	ADD_EXPRESSION: "ADD_EXPRESSION",
	REMOVE_EXPRESSION: "REMOVE_EXPRESSION",
	UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
	COOKIE_CLEANUP: "COOKIE_CLEANUP",
	ON_STARTUP: "ON_STARTUP",
	ADD_CACHE: "ADD_CACHE",
	INCREMENT_COOKIE_DELETED_COUNTER: "INCREMENT_COOKIE_DELETED_COUNTER",
	RESET_COOKIE_DELETED_COUNTER: "RESET_COOKIE_DELETED_COUNTER",
	UPDATE_SETTING: "UPDATE_SETTING",
	RESET_SETTINGS: "RESET_SETTINGS"
};

export default constants;
