name: GitHub Actions Testing

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'

jobs:
  _all:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GH_CXT: ${{ toJson(github) }}
        run:  echo "$GH_CXT"
      - name: Echo Fun
        env:
          CI: ${{ true }}
          GH_SECRETS: ${{ toJson(secrets) }}
        run:  |
          echo "CI $CI"
          echo "GITHUB_Ref:  $GITHUB_REF"
          echo "Secrets: $GH_SECRETS"
          echo "GITHUB_SECRETS: $GITHUB_SECRETS"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
