name: GitHub Actions Testing

on:
  push:
    branches:
      - 'ga_*'

jobs:
  all_jobs:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Echo Fun
      env:
        CI: true
        GITHUB_OBJ: ${{ github }}
        GITHUB_ACTIONS: ${{ github.actions }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SECRETS: ${{ secrets }}
      run:  |
        echo "CI $CI\nGithub: $GITHUB\nGH_OBJ: $GITHUB_OBJ\nSecrets: $SECRETS\nGH_SEC: $GITHUB_SECRETS"
