name: GitHub Actions Testing

on:
  push:
    branches:
      - 'ga_*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  one:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GH_CXT: ${{ toJson(github) }}
        run:  echo "$GH_CXT"
      - name: Echo Fun
        env:
          CI: ${{ true }}
          GH: ${{ toJson(github) }}
          GH_ACTIONS: ${{ github.actions }}
          GH_ACTIONS_1: ${{ GITHUB_ACTIONS }}
          GH_REF: ${{ github.ref }}
          GH_SECRETS: ${{ toJson(secrets) }}
        run:  |
          echo "CI $CI\nGitHub:  $GH\nActions:  $GH_ACTIONS\nRef: $GH_REF\nSecrets: $GH_SECRETS\nGH_SEC: $GITHUB_SECRETS/nGH_ACTIONS_1: $GH_ACTIONS_1\nGITHUB_A1: $GITHUB_ACTIONS"
