name: GitHub Actions Testing

on:
  push:
    branches:
      - 'ga_*'

jobs:
  one:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GH_CXT: ${{ toJson(github) }}
        run:  echo "$GH_CXT"
      - name: Echo Fun
        env:
          CI: ${{ true }}
          GH: ${{ github }}
          GH_OBJ: ${{ github }}
          GH_ACTIONS: ${{ github.actions }}
          GH_REF: ${{ github.ref }}
          GH_SECRETS: ${{ secrets }}
        run:  |
          echo "CI $CI\nGitHub:  $GITHUB\nGH_OBJ: $GITHUB_OBJ\nSecrets: $SECRETS\nGH_SEC: $GITHUB_SECRETS"
