name: Unsigned Test Build Artifact Links

on:
  pull_request:
    branches-ignore:
      - '_archived__**'

jobs:
  all_jobs:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Environments
        run: printenv
      - name: More Tets
        env:
          TEST: github
        run: |
          echo $env.TEST
          echo $TEST
