name: Unsigned Test Build Artifact Links

on:
  pull_request:
    branches-ignore:
      - '_archived__**'

jobs:
  local_test:
    name: Execute if non-fork repo
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.isLocal.outputs.result }}
    steps:
      - name: isLocal
        id: isLocal
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" === "${{ github.repository }}" ]]; then
            echo "::set-output name=result::0"
          else
            echo "::set-output name=result::1"
          fi
  all_jobs:
    name: Tests
    runs-on: ubuntu-latest
    needs: local_test
    steps:
      - name: Previous result
        run:  echo "${{ needs.local_test.outputs.result }}"
      - name: Environments
        run: printenv
      - name: GitHub Environments
        run: printenv | grep "GITHUB_"
      - name: More Tests
        run: |
          echo " ${{ toJSON(github.event) }}"
          echo ${{ github.workflow }}
          echo ${{ github.job }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.event_name }}
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.action }}
          echo ${{ toJSON(job) }}
