name: Unsigned Test Build Artifact Links

on:
  pull_request:
    branches-ignore:
      - '_archived__**'

jobs:
  all_jobs:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Environments
        run: printenv
      - name: GitHub Environments
        run: printenv | grep "GITHUB_"
      - name: More Tets
        env:
          TEST: github
        run: |
          echo $github
          echo $TEST
          echo ${{ github }}
