name: Unsigned Test Build Artifact Links

on:
  pull_request:
    branches-ignore:
      - '_archived__**'

jobs:
  all_jobs:
    name: Tests and Builds
    runs-on: ubuntu-latest
    needs: local_test
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: GitHub Environments
        run: printenv | grep "GITHUB_"
      - name: More Tests
        env:
          GH_JOBS: ${{ toJson(job) }}
        run: |
          echo "${{ toJSON(github.event) }}"
          echo "github.job: ${{ github.job }}"
          echo "github.run_id${{ github.run_id }}"
          echo "This is Pull Request Number: ${{ github.event.number }}"
          echo "$GH_JOBS"

