name: Unsigned Test Build Artifact Links

on:
  pull_request:
    branches-ignore:
      - '_archived__**'

jobs:
  local_test:
    name: Local Repo Check
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is Local
        run: |
          echo "Pull Request #: ${{ github.event.number }}"
          echo "Last Commit:    ${{github.event.after}}"
          echo "Head Repo Name: ${{github.event.pull_request.head.repo.full_name}}"
          echo "Repository:     ${{github.repository}}"
  all_jobs:
    name: Tests and Builds
    runs-on: ubuntu-latest
    needs: local_test
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: GitHub Environments
        run: printenv | grep "GITHUB_"
      - name: More Tests
        env:
          GH_GH: ${{ toJson(github) }}
          GH_JOBS: ${{ toJson(job) }}
        run: |
          echo "$GH_GH"
          echo "github.job: ${{ github.job }}"
          echo "$GH_JOBS"

