name: Unsigned Test Build Artifact Links

on:
  pull_request:
    branches-ignore:
      - '_archived__**'

jobs:
  all_jobs:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Environments
        run: printenv
      - name: GitHub Environments
        run: printenv | grep "GITHUB_"
      - name: More Tests
        run: |
          echo ${{ toJSON(github.event) }}
          echo ${{ github.workflow }}
          echo ${{ github.job }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.event_name }}
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.action }}
          echo ${{ toJSON(job) }}
