name: get-build-command
on:
  repository_dispatch:
    types: [get-build-command]

jobs:
  getBuild:
    name: Get Build for PR
    runs-on: ubuntu-latest
    steps:
      - name: List Data
        env:
          GH_GH: ${{ toJson(github) }}
        run: |
          printenv
      - name: Artifact URL Info
        id: arts
        env:
          GH_API: ${{ github.event.client_payload.github.payload.repository.url }}
          GH_RUNID: ${{ github.event.client_payload.slash_command.arg1 }}
          GH_BRANCH: ${{ github.event.client_payload.pull_request.head.ref }}
        run: |
          API_RUNS="$GH_API/actions/runs"
          echo "Run ID from Arg1:  $GH_RUNID"
          if [[ -z $GH_RUNID ]]; then
            echo "No Run ID Given.  Attempting to grab latest run from this PR Branch $GH_BRANCH"
            // https://api.github.com/repos/:owner/:repo/actions/runs?event=pull_request&status=success&branch=:branch
            curl -sf $API_RUNS?event=pull_request&status=success&branch=$GH_BRANCH > curl_latest.json
            EC=$?
            if [[ $EC != 0 ]]; then
              echo "Curl was not successful - returned $EC"
              echo "::set-output name=result::FAILED"
              echo "::set-output name=message::Internal Error / Could not fetch info from GitHub API at this time.  Curl returned error $EC."
            fi
            if [[ $(cat curl_latest.json | jq --raw-output '.total_count') -eq 0 ]]; then
              echo "No successful PR runs were made from branch $GH_BRANCH yet."
              echo "::set-output name=result::FAILED"
              echo "::set-output name=message::No Successful PR Runs were made from branch $GH_BRANCH yet."
            fi
            GH_RUNID=$(cat curl_latest.json | jq --raw-output '.workflow_runs[0].id')
            echo "Using RunID of $GH_RUNID parsed from branch $GH_BRANCH runs"
          fi
          echo "Artifact URL:  $GH_API/actions/runs/$GH_RUNID/artifacts"
          curl -sf $GH_API/actions/runs/$GH_RUNID/artifacts > curl_artifacts.json
          EC=$?
          if [[ $EC != 0 ]]; then
            echo ::set-output name=result::"FAILED"
            echo ::set-output name=message::"Received Error Message: $(cat curl_artifacts.json | jq --raw-output '.message')"
            exit $EC
          fi
          echo "$ARTS"
      - name: Reply Error in PR
        if: failure() && steps.arts.outputs.result == 'FAILED'
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            The `get-build` command did not execute successfully.  Additional information, if any, will be noted below.

            ${{ steps.arts.outputs.message }}
          reactions: eyes,confused
      - name: Create comment in PR
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            ### Get-build command was executed.

            This is a work in progress.
            See Action Workflow logs for output.
          reactions: hooray
