name: get-build-command
on:
  repository_dispatch:
    types: [get-build-command]

jobs:
  getBuild:
    name: Get Build for PR
    runs-on: ubuntu-latest
    steps:
      - name: List Data
        env:
          GH_GH: ${{ toJson(github) }}
        run: |
          printenv
      - name: Artifact URL Info
        id: arts
        env:
          GH_API: ${{ github.event.client_payload.github.payload.repository.url }}
          GH_RUNID: ${{ github.event.client_payload.slash_command.arg1 }}
        run: |
          echo "Run ID from Arg1:  $GH_RUNID"
          if [[ -z $GH_RUNID ]]; then
            echo "::set-output name=result::NO_RUNID"
            exit 1
          fi
          echo "Artifact URL:  $GH_API/actions/runs/$GH_RUNID/artifacts"
          ARTS=$(curl -sf $GH_API/actions/runs/$GH_RUNID/artifacts)
          if [[ $? != 0 ]]; then
            echo "::set-output name=result::ARTS_FAILED"
            exit 2
          fi
          jq
          echo "$ARTS"
      - name: Reply No Arg Error in PR
        if: failed() && steps.arts.outputs.result == 'NO_RUNID'
        uses: peter-evans/create-or-update-comment@1.4.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            The get-build command was executed with no arguments.  A run id is required at this time.
          reactions: eyes,confused
      - name: Reply Invalid Run ID in PR
        if: failed() && steps.arts.outputs.result == 'ARTS_FAILED'
        uses: peter-evans/create-or-update-comment@1.4.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            The get-build command did not get expected response.  Please check the run ID entered.
          reactions: eyes,confused
      - name: Create comment in PR
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            ### Get-build command was executed.

            This is a work in progress.
            See Action Workflow logs for output.
          reactions: hooray
