name: get-build-command
on:
  repository_dispatch:
    types: [get-build-command]

jobs:
  getBuild:
    name: Get Build for PR
    runs-on: ubuntu-latest
    steps:
      - name: List Data
        env:
          GH_GH: ${{ toJson(github) }}
        run: |
          printenv
      - name: Create comment in PR
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Get-build command was executed.  See Action Workflow logs for output.
          reactions: hooray
